<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        //**********************************************************************
        // Promise遵循Promise/A+规范
        // 接受一个函数executor作为参数，函数包含两个形参，分别是resolve和reject。
        // executor函数会被立即执行，
        // Promise内部会维护自己的状态，默认状态是否等待pending,
        // 执行resolve()状态会变为成功态(fulfilled)，执行reject()状态会变为失败态(rejected)
        // 如果executor函数执行中出现异常，状态会转变为reject状态。
        // then()在最后执行。

        // Promise基本使用
        let func = function() {
            new Promise((resolve, reject) => {
            console.log('执行 executor...');
            let randNum = Math.floor(Math.random() * 10);
            if (randNum % 2) {
                //触发成功
                resolve(randNum);
            } else {
                //触发失败
                reject(randNum);
            }
            }).then(ret => {
                //成功处理
                console.log('succeed: ' + ret);
            }, err => {
                //失败处理
                console.log('failed: ' + err);
            });
            console.log('middle print');
        }
        func();

        //**********************************************************************
        //链式调用
        // 1 then的成功或失败回调返回值假如是一个普通值，会将这个值传递给下次then的成功回调;
        // 2 then的成功或失败回调函数出错了，就走到下次then的失败回调函数;
        // 3 then的成功或失败回调函数中返回的是一个Promise,这个Promise的状态决定下一次then是走成功还是失败回调函数。
        // 之所以可以链式调用是因为then每次都会返回一个新的Promise对象（注意是新的Promise对象）。
        new Promise((resolve, reject) => {
            reject('err occurred by ...');
        }).then(value => {
            console.log('succeed: ', value);
        }, reason => {
            console.log('failed: ', reason);
            //undefined
        }).then(value => {
            console.log('success: ', value);
            throw new Error('test threw ...');
        }, reason => {
            console.log('failed: ', reason);
        }).then(value => {
            console.log('success: ', value);
        }, reason => {
            console.log('failed: ', reason);
            return new Promise((resolve, reject) => {
                if(Math.random() > 0.5) {
                    resolve('yes');
                } else {
                    reject('no');
                }
            });
        }).then(value => {
            console.log('success: ', value);
        }, reason => {
            console.log('failed: ', reason);
        });

        //链式调用的原理：then方法会返回一个新的Promise()实例
        
    </script>
</body>

</html>